export const ALL_NOTE_REQUEST = "ALL_NOTE_REQUEST";
export const ALL_NOTE_SUCCESS = "ALL_NOTE_SUCCESS";
export const ALL_NOTE_FAIL = "ALL_NOTE_FAIL";

export const NOTE_CREATE_REQUEST = "NOTE_CREATE_REQUEST";
export const NOTE_CREATE_SUCCESS = "NOTE_CREATE_SUCCESS";
export const NOTE_CREATE_FAIL = "NOTE_CREATE_FAIL";

export const UPDATE_NOTE_REQUEST = "UPDATE_NOTE_REQUEST";
export const UPDATE_NOTE_SUCCESS = "UPDATE_NOTE_SUCCESS";
export const UPDATE_NOTE_FAIL = "UPDATE_NOTE_FAIL";

export const NOTE_DELETE_REQUEST = "NOTE_DELETE_REQUEST";
export const NOTE_DELETE_SUCCESS = "NOTE_DELETE_SUCCESS";
export const NOTE_DELETE_FAIL = "NOTE_DELETE_FAIL";
